# -*- coding: utf-8 -*-
"""apresentacao10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LOWeVCjXaFYj8U71haanJW2RjZYL06UN
"""

from skimage import data 
from skimage import io 
from skimage import filters 

image = data.coins()  # ou matriz NumPy
image = data.coins()[0:95, 70:370] #sessão de imagem
edges = filters.sobel_h(image) # Encontre bordas em uma imagem usando o filtro Sobel
io.imshow(edges) # exibição da imagem

"""Galeria: https://scikit-image.org/docs/dev/auto_examples/
Filtros: https://scikit-image.org/docs/dev/api/skimage.filters.html?highlight=prewitt
"""

# Importação do NumPy para manipulação de variavéis e matplotlib para plotagem

import numpy as np
import matplotlib.pyplot as plt

# Carregue uma pequena seção da imagem
image = data.coins()[0:95, 70:370] #largura e altura

fig, axes = plt.subplots(ncols=2, nrows=3, #ncols = número de linhas, nrows = número de colunas
                         figsize=(8, 4)) #tamanho
ax0, ax1, ax2, ax3, ax4, ax5  = axes.flat # matriz 
ax0.imshow(image, cmap=plt.cm.gray) # Exibir dados como uma imagem 2D / uma imagem em tons de cinza
ax0.set_title('Original', fontsize=24) #título e tamanho
ax0.axis('off') #gráfico sem espinhas, linhas de eixo, marcas, rótulos de marca, rótulos de eixo e grade

"""https://peerj.com/articles/453/?report=reader

https://matplotlib.org/stable/search.html?q=ax0.axis%28%27off%27%29
https://scikit-image.org/docs/stable/api/skimage.filters.html

"""