# -*- coding: utf-8 -*-
"""atividade5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1km0pIjJ1mQQLL3vx-L3LGR2T5a4guJ14
"""

#a. Realize o download dos dados de forma manual e crie uma lista e uma tupla com as informações disponíveis no documento csv 
#(coloque pelo menos 1 linha por estado e 10 regiões de saúde diferentes, algo próximo de umas 40 linhas).

#Dados em 2021-01-01, semanaEpi 53

ListaCovid = ['RJ','AC','AM','RR','PA','AP','TO','MA','PI','CE']
ListaPopulacao = [17264943,881935,4144597,605761,8602865,845731,1572866,7075181,3273227,9132078]
ListaCasosAcumulados = [678601,41941,201574,68710,293802,68361,90536,200959,143179,335992]
ListaObitos = [39298,798,5295,787,7199,926,1236,4506,2840,9993] 

#Dados em 2021-02-23, semanaEpi 8 (MG); 2021-01-01 semanaEpi 53 (PA,AP); 2021-04-11 semanaEpi 15 (TO); 2021-05-16, semanaEpi 20 (MA);
# 2021-05-24,semanaEpi 21 (PI); 2021-03-26, semanaEpi 12 (PE); 2021-04-01, semanaEpi 13 (BA); 2021-01-02, semanaEpi 53 (RJ); 2021-01-21, semanaEpi 3 (PI)

TuplaCovid = ('MG','PA','AP','TO','MA','PI','PE','BA','RJ','PI')
TuplaPopulacao = (12459,1814,157698,5397,3434,9287,4891,951,8258,17264943,864845)
TuplaCasosAcumulados = (324,5120,812,200,15,386,951,403,435604,54542,)
TuplaObitos = (4,121,4,1,4,11,4,1,25608,1264)

#b. Mande printar na tela o número de casos acumulados para o estado do rio de janeiro tanto para a tupla quanto para a lista.

print('O número de casos acumulados no estado do Rio de Janeiro (Lista covid) é: ') 
print(ListaCasosAcumulados[1])
print('O número de casos acumulados no estado do Rio de Janeiro (Tupla covid) é: ')
print(TuplaCasosAcumulados[9])

#c. Apresente na tela todos os óbitos acumulados mostrando os casos apenas para o caso dos estados (sem mostrar regiões de saúde, etc..).

print(ListaCasosAcumulados)
print(TuplaCasosAcumulados)

# d. Assuma que os dados de óbitos novos para o estado da paraíba estejam errados em 10 unidades para menos. 
#Sobrescreva a informação tanto na lista quanto na tupla, corrigindo os dados.

print('Os dados de óbitos novos para o estado da paraíba estavam errados, a seguir o número correto:')
print(ListaObitos[5]+10)
print(TuplaObitos[2]+10)

"""**e. As duas operações foram possíveis (lista e tupla)? Justifique.** 
Não, pois em tupla não conseguimos alterar o índice. 
"""

#f. Crie uma nova lista com apenas dados de 1 estado e todos os municípios e adicione essa lista nova a lista já existente 
#(append ou insert).

# Roraima = ['Norte';'RR';'Amajari';14;140002;14001;'CENTRO NORTE';'2021-06-30';26;12796;1024;1;20;0;;;0,			
# 'Norte';'RR';'Alto Alegre';14;140005;14001;'CENTRO NORTE';'2021-06-30';26;15510;1417;2;32;1;;;1,			
# 'Norte';'RR';'Boa Vista';14;140010;14001;'CENTRO NORTE';'2021-06-30';26;399213;86278;213;1350;13;;;1,			
# 'Norte';'RR';'Bonfim';14;140017;14001;'CENTRO NORTE';'2021-06-30';26;18335;2162;0;31;0;;;1,			
# Norte;RR;Caracaraí;14;140020;14002;SUL;2021-06-30;26;21926;2463;2;51;0;;;0,			
# Norte;RR;Caroebe;14;140023;14002;SUL;2021-06-30;26;10169;1884;4;19;0;;;0,			
# Norte;RR;Iracema;14;140028;14002;SUL;2021-06-30;26;11950;1133;0;14;0;;;0,			
# Norte;RR;Mucajaí;14;140030;14001;CENTRO NORTE;2021-06-30;26;17853;2120;9;38;0;;;1,			
# Norte;RR;Normandia;14;140040;14001;CENTRO NORTE;2021-06-30;26;11290;480;0;26;0;;;0,			
# Norte;RR;Pacaraima;14;140045;14001;CENTRO NORTE;2021-06-30;26;17401;2192;4;34;0;;;0,			
# Norte;RR;Rorainópolis;14;140047;14002;SUL;2021-06-30;26;30163;2969;14;59;0;;;0,			
# Norte;RR;São João da Baliza;14;140050;14002;SUL;2021-06-30;26;8201;1366;13;9;0;;;0,			
# Norte;RR;São Luiz;14;140060;14002;SUL;2021-06-30;26;7986;589;0;11;0;;;0,			
# Norte;RR;Uiramutã;14;140070;14001;CENTRO NORTE;2021-06-30;26;10559;1153;1;10;0;;;0,		
# Norte;RR;Cantá;14;140017;14001;CENTRO NORTE;2021-06-30;26;18335;2162;0;31;0;;;1]	

ListaRR = ['Amajari','Alto Alegre','Boa Vista','Bonfim','Caracaraí','Caroebe','Iracema','Mucajaí','Normandia','Pacaraima','Rorainópolis','São João da Baliza','São Luiz','Cantá']
RegiaoRR = ['CENTRO NORTE','SUL']
populacaoRR = [12796, 15510, 399213, 18335, 21926, 10169, 11950, 17853, 11290, 17401, 30163, 8201, 7986, 10559, 18335]
CasosRR = [1024,1417,86278,2162,2463,1884,1133,2120,480,2192,2969,1366,589,1153,2162]
ObtosRR = [20,32,1350,31,51,19,14,38,26,34,59,9,11,10,31]


ListaCovid.append(ListaRR)
print(ListaCovid)
ListaPopulacao.append(populacaoRR )
print(ListaPopulacao)
ListaCasosAcumulados.append(CasosRR)
print(ListaCasosAcumulados)
ListaObitos.append(ObtosRR)
print(ListaObitos)

#g. Remova da lista os dados das regiões de saúde.

ListaCovid.append(ListaRR)
print(ListaCovid)
ListaCovid.remove(ListaRR)
print(ListaCovid)

# h. Verifique se a soma dos dados dos municípios na data de 18/08/2020 é igual ao dado da
# lista, mostrando na tela apenas se for verdadeiro.
#i. Retorne o tamanho total da lista.


#''''''''''''''''Cálculo feito com dados de 2021-06-30 no estado de RR''''''''''''''''''''''''

print('Verificação dos dados')
print(sum(ObtosRR))
ObtosRR = [1735]
ObtosRRverificados = ObtosRR
print(ObtosRR is ObtosRRverificados)

#j. Verifique qual é o maior valor numérico de óbitos novos e o menor valor numérico de óbitos novos.

novosObtosRR = [0,1,13,0,0,0,0,0,0,0,0,0,0,0,0]
print(max(novosObtosRR))
print(min(novosObtosRR))

#k. Crie um dicionário de forma que seja possível encontrar os municípios associados a um
#estado específico e extrair os dados de casos novos em apenas um comando.

NovosCasosRR = {'Amajari':1,'Alto Alegre':2,'Boa Vista':213,'Bonfim':0,'Caracaraí':2,'Caroebe':4,'Iracema':0,'Mucajaí':9,'Normandia':0,'Pacaraima':4,'Rorainópolis':14,'São João da Baliza':13,'São Luiz':0,'Cantá':1}
print(NovosCasosRR)

#l. Extraia os dados de Teresina/PI apresentando os casos novos com um print.

DadosTeresina = ('Nordeste','PI','Teresina',22,221100,22004,'ENTRE RIOS','2021-06-30',26,864845,100215,94,2451,11,1)	
print(DadosTeresina[12])