# -*- coding: utf-8 -*-
"""atividade4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t96K3yih3NmdMG8KMGdtSrR1XgBsBoAz
"""

#a. Requisito 1: Habituação
#i. Se o animal está habituado, registrar em uma variável
entrar_na_caixa = int(input('O sagui entrou na caixa? 1-> Sim 2-> Não\n'))
#acerto = int(input('O sagui acertou 20 vezes\n')) #10 vezes limite superior de acerto

if (entrar_na_caixa):
  print('O animal está habituado')

#b. Requisito 2: Regime de aproximações sucessivas
#i. Iniciar a variável com 30centímetros
#ii. Se a variável de aproximação diminuiu (animal aproximou), liberar 0,5ml de rec
#iii. Se animal tocou na barra 20x, retornar que o experimento passou para a próxima etapa

entrar_na_caixa = bool(input('O sagui entrou na caixa? 1-> Sim 2-> Não \n'))
if (entrar_na_caixa):
  print('Inicio')

distancia = bool(input('O sagui percorreu uma nova distância? 1-> Sim 2-> Não\n'))
if (entrar_na_caixa):
  print('liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 2 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra (3)? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 3 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 4 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 5 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 6 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 7 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 8 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 9 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 10 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 11 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 12 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 13 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 14 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 15 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 16 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 17 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 18 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 19 > liberar 0,5ml de recompensa')

tocar_na_barra = bool(input('O sagui tocou na barra? 1-> Sim 2-> Não\n'))
if (tocar_na_barra):
  print('escore: 20 > liberar 0,5ml de recompensa\n')
  print('o experimento passou para a próxima etapa')

# iv. Se o som1 foi emitido e o animal tocou na barra esquerda, liberar 0,5ml de rec
# v. Caso contrário não liberar nada
# vi. Se o som2 foi emitido e o animal tocou na barra direita, liberar 0,5ml
# de rec
# vii. Caso contrário não liberar nada
# viii. Se o experimento foi realizado 50x em 30min, apresentar que o experimento seguirá para a próxima fase.

som_Phee = int(input('O animal tocou na barra esquerda ao som Phee? 1-> Sim 2-> Não\n'))
som_Trill = int(input('O animal tocou na barra direita ao som Trill? 1-> Sim 2-> Não\n'))

if (som_Phee ==1 and som_Trill ==1 ):
  print('acerto 1: liberar 0,5ml de recompensa')
elif (som_Phee ==2 and som_Trill ==2):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 2: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Phee ==1 and som_Trill ==1 ):
  print('acerto 3: 0,5ml de recompensa')
elif (som_Phee ==2 and som_Trill ==2):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 4: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Phee ==1 and som_Trill ==1 ):
  print('acerto 5: liberar 0,5ml de recompensa')
elif (som_Phee ==2 and som_Trill ==2):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 6: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Phee ==1 and som_Trill ==1 ):
  print('acerto 7: liberar 0,5ml de recompensa')
elif (som_Phee ==2 and som_Trill ==2):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 8: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Phee ==1 and som_Trill ==1 ):
  print('acerto 9: liberar 0,5ml de recompensa')
elif (som_Phee ==2 and som_Trill ==2):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 10: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Phee ==1 and som_Trill ==1 ):
  print('acerto 11: liberar 0,5ml de recompensa')
elif (som_Phee ==2 and som_Trill ==2):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 12: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa') 

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 13: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 14: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 15: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 16: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 17: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 18: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 19: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')


if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 20: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 21: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')  

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 22: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 23: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 24: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 24: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 25: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 26: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 27: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 28: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 29: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 30: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 31: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 32: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 33: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 34: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 35: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 36: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 37: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 38: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 39: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 40: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 41: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 42: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 43: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 44: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 45: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 46: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 47: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 48: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 49: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

if (som_Trill =='1' and som_Trill =='1' ):
  print('acerto 50: liberar 0,5ml de recompensa')
elif (som_Trill =='2' and som_Trill =='2'):
  print('não liberar recompensa')

print('Fim de treino')

tempototal = str(input('O experimento foi realizado 50x em 30min ? 1-> Sim 2-> Não\n'))
if (tempototal == 1):
  print('O experimento seguirá para a próxima fase.')
elif (tempototal =='2' and tempototal =='2'):
  print('O experimento deverá ser repetido')
else:
    print('O tempo de 30 min foi ultrapassado')

print("Fim do programa!")