# -*- coding: utf-8 -*-
"""atividade6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Yo_XTkZdYdfQIAD__J1euTHu41o_Y10
"""

#Início 

mensagem1 = ('Olá, neste programa iremos simular um passo  a passo de procedimento cirúrgico para pequenos animais.')
print(mensagem1)
passo1 = int(input('Para iniciar o procedimento digite: 1->Sim 2->Não'))
print(bool(passo1))

#Etapa I. Procedimento de anestesia: Pode-se utilizar uma diversidade de fármacos para anestesia os animais,
# dentre eles Ketamina e xilazina utilizados em conjunto, halotano (gasoso).
# Verificar a dosagem correta de acordo com o peso dos animais.

Mensagem2 = ('Passo 1: selecione o tipo de anestesia:')
print(Mensagem2)
anestesia = int(input('A Ketamina associada a Xilazina, halotano (gasoso) pode produzir sedação por tempo hábil de 30 min,\n deseja utilizar Halotano ? Pressione 1-> Sim 2-> Não'))
if (anestesia == 1):
  print('Halotano selecionado \n') 

Mensagem3 = ('Passo 1.1: selecione a dosagem correta de acordo com o peso do animal'))
print(Mensagem3)
Mensagem4 = ('Recomendação 02 ml de Ketamina (50mg/ml) mais 500 l de xilazina(20mg/ml) mais 7,5ml de água.')
print(Mensagem4)

dose = int(input('\n a dose está correta de acordo com o peso do animal ? Pressione 1-> Sim 2-> Não'))
print(bool(dose))

if dose ==1:
  print('Próxima eatapa: posicionamento do animal')
elif not dose:
  print('Ajuste a dose')
else:
  print('Se o animal ainda estiver tendo reflexos ou vier a tê-los administrar mais 10% da dose')

# II. Depois do anestésico ter feito efeito, deve-se posicionar o animal no estereotáxico. As
# barras que suportam o peso do animal devem ser posicionadas no ouvido externo do
# animal. Normalmente o animal dá uma pequena piscada, devido ao estímulo da
# musculatura responsável por este movimento. Em seguida verificar a angulação da
# cabeça do animal, a qual deve estar sem diferenças de angulação entre o bregma e o
# lambda, para ter uma superfície de cirurgia plana.

Mensagem5 = ('Passo2: Posicionamento do animal')
print(Mensagem5)

passo2_1 = print('Posicione as barras que suportam o peso do animal no ouvido externo.')
barra = int(input('O animal piscou ao ser posiconado? 1-> Sim 2-> Não'))

if barra ==1:
  print('O animal está bem posicionado? 1-> Sim 2-> Não \n')
elif not barra:
  print('Ajuste o posicionamento')
else:
  print('O animal está mal posicionado')

Mensagem6 = ('Passo2.1: Marcação do campo cirúrgico')
print(Mensagem6)

passo2_2 = print('Verifique a angulação da cabeça do animal')
Mensagem7 = ('A angulação da cabeça do animal deve estar sem diferenças de angulação entre o bregma e o lambda')
print('Mensagem7')
angulacao = int(input('O campo está bem posicionado? 1-> Sim 2-> Não'))

if angulacao ==1:
  print('Próxima eatapa: Limpeza do campo de trabalho:')
elif not angulacao:
  print('Ajuste o campo')
else:
  print('Ajuste o campo')

# III. Limpeza do campo de trabalho: Este procedimento requer o cumprimento de algumas
# etapas: Retirada da pelagem que recobre a parte superior da calota craniana, Retirada
# dos tecidos moles (epiderme, derme e tecido conjuntivo) até alcançar a parte óssea da
# caixa craniana. Por último e não menos importante deve-se limpar a calota craniana de
# qualquer resto de “pele” que esteja sobrando utilizando H 2 O 2 10 volumes.

Mensagem8 = ('Passo3: Limpeza do campo de trabalho')
print(Mensagem8)
Mensagem9 = ('Este procedimento requer o cumprimento de algumas etapas:')
print(Mensagem9)
etapas = {'Retirada da pelagem':(),'Retirada dos tecidos moles':('epiderme','derme','tecido','conjuntivo')}
for etapas in etapas:
  print(etapas)

# IV. Com o animal em posição e com o campo cirúrgico devidamente limpo, utiliza-se uma
# pequena camada de poliacrilato em todo o perímetro externo para evitar
# sangramentos.

Mensagem10 = ('Passo4: insira uma pequena camada de poliacrilato em todo o perímetro externo para evitar sangramentos.')
print(Mensagem10)

Mensagem11 = ('Passo 5: Escolha um ponto para a fixação de parafusos, de preferência na parte posterior da calota craniana.')
print(Mensagem11)

fixacao = int(input('Os parafusos estão bem posicionados? 1-> Sim 2-> Não'))

if fixacao ==1:
  print('Calcule o posicionamento AnteroPosterior (AP), LateroLateral (LL) e DorsoVentral(DV)')
elif not fixacao:
  print('Ajuste os parafusos')
else:
  print('Ajuste os parafusos')

input('AP:')
input('LL:')
input('DV:')

# VI. Após estes cálculos feitos é hora de localizar os pontos de inserção das cânulas-guia.
# Assim que estes pontos forem localizados é necessário fazer furos para a introdução
# das cânulas-guia. A localização destes pontos deve ser definida pelos valores
# encontrados nos cálculos AnteroPosterior (6,00) e LateroLateral (3,63 e 3,03). Deve-se
# escolher qual dos hemisférios vai ser colocada a primeira cânula, daí os dois valores
# para as medidas LL.

Mensagem12 = ('Passo 6: Localize os pontos de inserção das cânulas-guia')
print(Mensagem12)

canula = int(input('Selecione o hemisfério para colocação da primeira cânula ? Pressione 1-> HD 2-> HE'))
print(bool(canula))
print('O hemisfério selecionado foi: %s' %(canula))

# VII. Depois de posicionar a agulha, fazer um furo com a broca até alcançar as meninges. A
# não perfuração das meninges é o procedimento ideal, e para conseguir isso apoie a
# mão que segura a broca contra o assoalho ou ao estereotáxico e perfure o crânio a +-
# 45 0 de angulação.


Mensagem13 = ('Passo7: Descrição do procedimento')
print(Mensagem13)
Procedimentos = ['Faça um furo com a broca até alcançar as meninges','Perfure o crânio a +-45 0 de angulação','Introduza a cânula-guia até o valor DorsoVentral (4,00)','Drene qualquer sangue ou líquido cefalorraquidiano']
print(Procedimentos)

# XIII. Levantar bem devagar seguindo as instruções do item contida no item 11. Acomodar o
# animal em uma caixa aquecida por uma lâmpada e sem outros animais acordados.
# Assim que o animal despertar colocá-lo de volta a sua caixa-moradia.

Mensagem14 = ("Passo8: Acomode o animal em uma caixa aquecida por uma lâmpada e sem outros animais acordados.")
print(Mensagem14)
fim = input('O animal está acomodado? Pressione 1-> Sim 2-> Não')
while fim == 1:
  print('Fim do programa')