#Exercício do cálculo do IMC
print("")
print("")
print("------------------------")
print("")
print("Calcule seu IMC")
peso = float(input("Informe o peso: \n"))
altura = float(input("Informe o altura: \n"))
imc = (peso / (altura*altura))
print("")
print ('IMC | % .2f |  < 17 - Usuário muito abaixo do peso? '% imc, imc <17)
print ('IMC | % .2f | >= 17 e IMC | % .2f | <= 18.5 - Usuário peso normal? '% (imc,imc), (imc >=17) and (imc <=18.5))
print ('IMC | % .2f | >= 18.5 e IMC | % .2f | <= 25 - Usuário peso normal? '% (imc,imc), (imc >=18.5)and(imc <=25))
print ('IMC | % .2f | >= 25 e IMC | % .2f | <= 30 - Usuário peso normal? '% (imc,imc), (imc >=25)and(imc <=30))
print ('IMC | % .2f | > 30 - Usuário muito acima do peso? '% imc, (imc >30))